#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# ./Allrun.pre

restore0Dir

runApplication $(getApplication)

# Run postProcess
postProcess -func 'components(U)' && postProcess -func 'writeCellCentres'
#------------------------------------------------------------------------------
